### ISSUE TITLE
Please rebase in the future

### ISSUE THREAD

**Issue by liang799** [stevelimly/react-tic-tac-toe#7]
![image](https://user-images.githubusercontent.com/71926348/200488545-a870f545-cd8e-4d1c-b999-7ad35e3521b9.png)
![image](https://user-images.githubusercontent.com/71926348/200488608-577792a3-c3b7-4f5e-84ec-3cf06278bf24.png)

**Comment by stevelimly** [comment]
Got it, I didn't notice that, thanks for your reminds
